TARGET = sensor_parameter_safetyCMD \
	get_distance_safetyCMD \
	get_full_step_distance_safetyCMD \
	get_distance_intensity_safetyCMD \
	get_distance_continuous_safetyCMD \
	get_distance_intensity_continuous_safetyCMD \
	get_area_safetyCMD get_status_safetyCMD \
	get_detection_log_safetyCMD \
	clear_detection_log_safetyCMD

URG_LIB = ../../src/liburg_c.a

include ../../build_rule.mk

CFLAGS = -O2 $(INCLUDES) -I../../include/c
LDLIBS = -lm `/bin/sh ld_wsock.sh` `/bin/sh ld_setupapi.sh`

all : $(TARGET)

clean :
	$(RM) *.o $(TARGET) *.exe

$(TARGET) : $(URG_LIB)

$(URG_LIB) :
	cd $(@D)/ && $(MAKE) $(@F)
